export const FETCH_CITIES_PENDING = "@cities/FETCH_CITIES_PENDING";
export const FETCH_CITIES_ERROR = "@cities/FETCH_CITIES_ERROR";
export const FETCH_CITIES_FULFILLED = "@cities/FETCH_CITIES_FULFILLED";
