export const FETCH_CITIES_PENDING = "@cities/FETCH_CITIES_PENDING";
export const FETCH_CITIES_ERROR = "@cities/FETCH_CITIES_ERROR";
export const FETCH_CITIES_FULFILLED = "@cities/FETCH_CITIES_FULFILLED";
export const FETCH_FLIGHTS_PENDING = "@flights/FETCH_FLIGHTS_PENDING";
export const FETCH_FLIGHTS_ERROR = "@flights/FETCH_FLIGHTS_ERROR";
export const FETCH_FLIGHTS_FULFILLED = "@flights/FETCH_FLIGHTS_FULFILLED";
